export const BANNER_HEIGHT_TABLET = 880;
export const BANNER_HEIGHT_MOBILE = 500;

export const SMART_PANEL_CONTAINER_WIDTH_MOBILE = 290;
export const SMART_PANEL_CONTAINER_WIDTH_TABLET = 580;
export const SMART_PANEL_CONTAINER_WIDTH_LAPTOP = 1000;
export const SMART_PANEL_CONTAINER_HEIGHT = 180;

export const STORYBOARD_VIDEO_WIDTH_MOBILE = 300;
export const STORYBOARD_VIDEO_WIDTH_TABLET = 500;
export const STORYBOARD_VIDEO_WIDTH_LAPTOP = 600;
