version: '3.1'

services:
  aodnportal:
    container_name: aodn-portal-v2
    build: .
    image: https://ogcapi-edge.mvp.aodn.org.au/
    network_mode: "host"
    env_file:
      - sample.env
    volumes:
      - /tmp:/tmp