export const SEARCH_PAGE_CONTENT_CONTAINER_HEIGHT_ABOVE_LAPTOP = "85vh";
export const SEARCH_PAGE_CONTENT_CONTAINER_HEIGHT_UNDER_LAPTOP = "auto";

export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_ABOVE_LAPTOP = "100%";
export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_UNDER_LAPTOP = "65vh";

export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_FULL_MAP_TABLET = "80vh";
export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_FULL_MAP_MOBILE = "70vh";
export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_FULL_LIST = 0;

export const SEARCH_PAGE_RESULT_SECTION_CONTAINER_MIN_WIDTH = 500;

export const SEARCH_PAGE_REFERER = "SEARCH_PAGE";
export const DETAIL_PAGE_REFERER = "DETAIL_PAGE";
