import { HEADER_HEIGHT } from "@/app/layout/constant";

// Site footer is hidden on search, so fill the remaining viewport below the header
export const SEARCH_PAGE_CONTENT_CONTAINER_HEIGHT_ABOVE_LAPTOP = `calc(100vh - ${HEADER_HEIGHT}px)`;
export const SEARCH_PAGE_CONTENT_CONTAINER_HEIGHT_UNDER_LAPTOP = "auto";

export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_ABOVE_LAPTOP = "100%";
export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_UNDER_LAPTOP = "65vh";

export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_FULL_MAP_TABLET = "80vh";
export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_FULL_MAP_MOBILE = "70vh";
export const SEARCH_PAGE_MAP_CONTAINER_HEIGHT_FULL_LIST = 0;

export const SEARCH_PAGE_RESULT_SECTION_CONTAINER_MIN_WIDTH = 500;
export const SEARCH_PAGE_RESULT_SECTION_CONTAINER_MAX_WIDTH = 600;
