services:
  web:
    build:
      context: ..
      dockerfile: playwright/Dockerfile.web
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
      - /app/node_modules

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - web
    environment:
      - BASE_URL=http://web:5173
      - POETRY_VIRTUALENVS_CREATE=false
    volumes:
      - ./:/app
