export const TEXT_FIELD_MIN_WIDTH = 150;

export const SEARCHBAR_EXPANSION_WIDTH = 0.7;

export const POPUP_MIN_WIDTH_MOBILE = 250;
export const POPUP_MIN_WIDTH_TABLET = 700;
export const POPUP_MIN_WIDTH_LAPTOP = 1000;
