export const CARD_ID = {
  GET_START: 1,
  SURFACE_WAVES: 2,
  REEF: 4,
  LOCATION: 5,
  ADVANCED_SEARCH: 6,
  TUTORIAL: 7,
  ALL_TOPICS: 8,
  OCEAN_BIOTA: 9,
  EXPLORER_ON_MAP: 10,
  FISHERY: 11,
  TOURISM: 12,
  SATELITE: 3,
};
