name: Build/Deploy Edge

on:
  push:
    branches:
      - 5319-cicd
    paths-ignore:
      - '**/*.md'
      - '.github/environment/**'

permissions:
  id-token: write
  contents: read

jobs:
  build_push:
    runs-on: ubuntu-latest
    environment: edge
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Vite
        run: yarn global add vite

      - name: Install Dependencies
        run: yarn install --force

      - name: Build Website
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
            name: build
            path: ./dist
            retention-days: 1

      - name: print
        run: |
          echo ${{ vars.AWS_REGION }}
          echo ${{ vars.AWS_ROLE_ARN }}

      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

  edge_deploy:
    environment: edge
    runs-on: ubuntu-latest
    needs: build_push
    env:
      DIST: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Retrieve Parameters - ssm parameter store
        id: getParameters
        run: |
          # Replace '--path' with your specific path from Parameter Store
          bucket=$(aws ssm get-parameter --name "/core/aodn-portal-v2/edge-bucket" --query 'Parameter.Value' --output text)
          distribution_id=$(aws ssm get-parameter --name "/core/aodn-portal-v2/edge-cloudfront-distribution-id" --query 'Parameter.Value' --output text)
          echo "BUCKET=$bucket" >> "$GITHUB_ENV"
          echo "DISTRIBUTION_ID=$distribution_id" >> "$GITHUB_ENV"
  
      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }} --region ${{ vars.AWS_REGION }}

      - name: Clear cloudfront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ env.DISTRIBUTION_ID }} \
          --paths "/*" \
          --region ${{ vars.AWS_REGION }}