name: Portal App build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  dev-build:
    name: Build app
    runs-on: ubuntu-latest
    env:
      CI: ""
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          node --version
          npm ci --production

      - name: Build Static Website
        run: npm run build

  dev-push:
    name: Publish app
    runs-on: ubuntu-latest
    env:
      AWS_ROLE_TO_ASSUME: arn:aws:iam::704910415367:role/aodn-portal-v2
      BUCKET: portal2.aodn.org.au
      DIST: build
      DIST_ID: EUL4XIP4OACLK
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
  
      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }} --region ap-southeast-2

      - name: Clear cloudfront cache
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*" \
          --region us-east-1
