name: Build/Deploy Edge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/environment/**'

permissions:
  id-token: write
  contents: read

jobs:

  trigger_edge_build_deploy:
    uses: ./.github/workflows/trigger_build_deploy.yml
    with:
      app_name: portal
      environment: edge
    secrets: inherit