name: lint and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# cancel currently running workflow from the same PR or branch
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Enable Corepack
        run: corepack enable

      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install --immutable
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
