name: Lint, Test and Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# cancel currently running workflow from the same PR or branch
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Corepack
        run: corepack enable

      - uses: actions/checkout@v5
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      - run: |
          yarn install --immutable
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
