name: Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  id-token: write
  contents: read

jobs:
  trigger_staging_build_deploy:
    uses: ./.github/workflows/trigger_build_deploy.yml
    with:
      app_name: portal
      environment: staging
    secrets: inherit

  trigger_production_build_deploy:
    needs: [trigger_staging_build_deploy]
    uses: ./.github/workflows/trigger_build_deploy.yml
    with:
      app_name: portal
      environment: production
    secrets: inherit