name: Build and run UI test

on:
  pull_request:
    branches:
      - main

jobs:
  ui_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install yarn
        run: |
          yarn install --immutable

      - name: Run playwright tests
        run: yarn playwright

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: |
            playwright/reports/
            playwright/test-results/
          retention-days: 7
